/**
 * Formats Description
 * @type {Object.<string, string>}
 * @readonly
 */
enum EFormat {
    VINYL = 'Vinyl',
    CD = 'CD',
    CASSETTE = 'Cassette',
    DVD = 'DVD',
    BOXSET = 'Box Set',
    CDR = 'CDr',
    ALLMEDIA = 'All Media',
    SHELLAC = 'Shellac',
    FLEXIDISC = 'Flexi-disc',
    SACD = 'SACD',
    VHS = 'VHS',
    BLURAY = 'Blu-ray',
    EIGHTTRACKCARTRIDGE = '8-Track Cartridge',
    LASERDISC = 'Laserdisc',
    HYBRID = 'Hybrid',
    LATHECUT = 'Lathe Cut',
    DVDR = 'DVDr',
    FILE = 'File',
    REELTOREEL = 'Reel-To-Reel',
    CDV = 'CDV',
    MINIDISC = 'Minidisc',
    ACETATE = 'Acetate',
    MEMORYSTICK = 'Memory Stick',
    EDISONDISC = 'Edison Disc',
    FLOPPYDISK = 'Floppy Disk',
    DCC = 'DCC',
    PATHÉDISC = 'Pathé Disc',
    FOURTRACKCARTRIDGE = '4-Track Cartridge',
    HDDVD = 'HD DVD',
    UMD = 'UMD',
    BETAMAX = 'Betamax',
    BETACAMSP = 'Betacam SP',
    BLURAYR = 'Blu-ray-R',
    SELECTAVISION = 'SelectaVision',
    CYLINDER = 'Cylinder',
    MICROCASSETTE = 'Microcassette',
    VHD = 'VHD',
    PLAYTAPE = 'PlayTape',
    UMATIC = 'U-matic',
    VIDEO8 = 'Video8',
    NTCASSETTE = 'NT Cassette',
    DAT = 'DAT',
    MINIDV = 'MiniDV',
    VIDEO2000 = 'Video 2000',
    TWELVE = '12"',
    SEVEN = '7"',
    BETACAM = 'Betacam',
    ELCASET = 'Elcaset',
    HDDVDR = 'HD DVD-R',
    LP = 'LP',
    POCKETROCKER = 'Pocket Rocker',
    RCATAPECARTRIDGE = 'RCA Tape Cartridge',
    WIRERECORDING = 'Wire Recording',
}

export default EFormat
