// cspell: disable
/**
 * FormatDescriptions
 */
export type FormatDescriptionType =
    | '1 ⅞ ips'
    | '1"'
    | '10"'
    | '10.5" NAB Reel'
    | '11"'
    | '12"'
    | '15 ips'
    | '15/16 ips'
    | '16 ⅔ RPM'
    | '16"'
    | '16mm'
    | '2 Minute'
    | '2"'
    | '2-Track Mono'
    | '2-Track Stereo'
    | '21cm'
    | '25cm'
    | '27cm'
    | '29cm'
    | '3 Minute'
    | '3 ¾ ips'
    | '3"'
    | '3" Cine Reel'
    | '3.5"'
    | '30 ips'
    | '33 ⅓ RPM'
    | '35cm'
    | '35mm'
    | '3½"'
    | '4 Minute'
    | '4"'
    | '4-Track Mono'
    | '4-Track Stereo'
    | '45 RPM'
    | '4K'
    | '5"'
    | '5" Cine Reel'
    | '5.25"'
    | '50cm'
    | '5½"'
    | '6"'
    | '6" Cine Reel'
    | '6½"'
    | '7 ½ ips'
    | '7"'
    | '7" Cine Reel'
    | '78 RPM'
    | '8 ⅓ RPM'
    | '8"'
    | '80 RPM'
    | '8K'
    | '9"'
    | '90 RPM'
    | 'AAC'
    | 'AIFC'
    | 'AIFF'
    | 'ALAC'
    | 'AMR'
    | 'APE'
    | 'AVCD'
    | 'AVI'
    | 'Advance'
    | 'Album'
    | 'Ambisonic'
    | 'Bioplastic'
    | 'Blu-ray Audio'
    | 'Business Card'
    | 'CD+G'
    | 'CD-ROM'
    | 'CD-Record'
    | 'CDi'
    | 'Card Backed'
    | 'Club Edition'
    | 'Compilation'
    | 'Concert'
    | 'Copy Protected'
    | 'DFF'
    | 'DSF'
    | 'DVD-Audio'
    | 'DVD-Data'
    | 'DVD-Video'
    | 'DVDplus'
    | 'Deluxe Edition'
    | 'Disc Image'
    | 'Double Sided'
    | 'DualDisc'
    | 'EP'
    | 'Enhanced'
    | 'Etched'
    | 'FLAC'
    | 'FLV'
    | 'HDCD'
    | 'Hybrid'
    | 'Jukebox'
    | 'LP'
    | 'Limited Edition'
    | 'MOV'
    | 'MP2'
    | 'MP3'
    | 'MP3 Surround'
    | 'MPEG Video'
    | 'MPEG-4 Video'
    | 'Maxi-Single'
    | 'Mini'
    | 'Mini-Album'
    | 'Minimax'
    | 'Mispress'
    | 'Misprint'
    | 'Mixed'
    | 'Mixtape'
    | 'Mono'
    | 'Multichannel'
    | 'NTSC'
    | 'Numbered'
    | 'Opus'
    | 'PAL'
    | 'Partially Mixed'
    | 'Partially Unofficial'
    | 'Picture Disc'
    | 'Promo'
    | 'Quadraphonic'
    | 'RA'
    | 'RM'
    | 'Reissue'
    | 'Remastered'
    | 'Repress'
    | 'SECAM'
    | 'SHN'
    | 'SVCD'
    | 'SWF'
    | 'Salon'
    | 'Sampler'
    | 'Shape'
    | 'Single'
    | 'Single Sided'
    | 'Special Edition'
    | 'Stereo'
    | 'Styrene'
    | 'TTA'
    | 'Test Pressing'
    | 'Transcription'
    | 'Unofficial Release'
    | 'VCD'
    | 'VinylDisc'
    | 'WAV'
    | 'WMA'
    | 'WMV'
    | 'WavPack'
    | 'White Label'
    | 'XRCD'
    | 'ogg-vorbis'
    | '¼"'
    | '½"'
    | '⅛"'
