// cspell: disable
/**
 * From
 */
export type FromType =
    | 'Afghanistan'
    | 'Albania'
    | 'Algeria'
    | 'American Samoa'
    | 'Andorra'
    | 'Angola'
    | 'Anguilla'
    | 'Antarctica'
    | 'Antigua and Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Aruba'
    | 'Australia'
    | 'Austria'
    | 'Azerbaidjan'
    | 'Bahamas'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bermuda'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bosnia-Herzegovina'
    | 'Botswana'
    | 'Bouvet Island'
    | 'Brazil'
    | 'British Indian Ocean Territory'
    | 'Brunei Darussalam'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Cape Verde'
    | 'Cayman Islands'
    | 'Central African Republic'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Christmas Island'
    | 'Cocos (Keeling) Islands'
    | 'Colombia'
    | 'Comoros'
    | 'Congo'
    | 'Cook Islands'
    | 'Costa Rica'
    | 'Croatia'
    | 'Cuba'
    | 'Cyprus'
    | 'Czech Republic'
    | 'Denmark'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'East Timor'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Ethiopia'
    | 'Falkland Islands'
    | 'Faroe Islands'
    | 'Fiji'
    | 'Finland'
    | 'Former Czechoslovakia'
    | 'Former USSR'
    | 'France'
    | 'France (European Territory)'
    | 'French Guyana'
    | 'French Southern Territories'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Gibraltar'
    | 'Greece'
    | 'Greenland'
    | 'Grenada'
    | 'Guadeloupe (French)'
    | 'Guam (USA)'
    | 'Guatemala'
    | 'Guinea'
    | 'Guinea Bissau'
    | 'Guyana'
    | 'Haiti'
    | 'Heard and McDonald Islands'
    | 'Honduras'
    | 'Hong Kong'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Israel'
    | 'Italy'
    | "Ivory Coast (Cote D'Ivoire)"
    | 'Jamaica'
    | 'Japan'
    | 'Jordan'
    | 'Kazakhstan'
    | 'Kenya'
    | 'Kiribati'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Laos'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macau'
    | 'Macedonia'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Martinique (French)'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mayotte'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova, Republic of'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Montserrat'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'Netherlands Antilles'
    | 'Neutral Zone'
    | 'New Caledonia (French)'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Niue'
    | 'Norfolk Island'
    | 'Northern Ireland'
    | 'Northern Mariana Islands'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'Panama'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Pitcairn Island'
    | 'Poland'
    | 'Polynesia (French)'
    | 'Portugal'
    | 'Puerto Rico'
    | 'Qatar'
    | 'Reunion (French)'
    | 'Romania'
    | 'Russian Federation'
    | 'Rwanda'
    | 'S. Georgia & S. Sandwich Isls.'
    | 'Saint Helena'
    | 'Saint Kitts & Nevis Anguilla'
    | 'Saint Lucia'
    | 'Saint Pierre and Miquelon'
    | 'Saint Tome (Sao Tome) and Princi'
    | 'Saint Vincent & Grenadines'
    | 'Samoa'
    | 'San Marino'
    | 'Saudi Arabia'
    | 'Select your country'
    | 'Senegal'
    | 'Serbia'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Slovak Republic'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'South Africa'
    | 'South Korea'
    | 'Spain'
    | 'Spain (Canary Islands)'
    | 'Sri Lanka'
    | 'Sudan'
    | 'Suriname'
    | 'Svalbard and Jan Mayen Islands'
    | 'Swaziland'
    | 'Sweden'
    | 'Switzerland'
    | 'Syria'
    | 'Tadjikistan'
    | 'Taiwan'
    | 'Tanzania'
    | 'Thailand'
    | 'Togo'
    | 'Tokelau'
    | 'Tonga'
    | 'Trinidad and Tobago'
    | 'Tunisia'
    | 'Turkey'
    | 'Turkmenistan'
    | 'Turks and Caicos Islands'
    | 'Tuvalu'
    | 'USA Minor Outlying Islands'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'United Kingdom (Channel Islands)'
    | 'United States'
    | 'Uruguay'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Vatican City State'
    | 'Venezuela'
    | 'Vietnam'
    | 'Virgin Islands (British)'
    | 'Virgin Islands (USA)'
    | 'Wallis and Futuna Islands'
    | 'Western Sahara'
    | 'Yemen'
    | 'Yugoslavia'
    | 'Zaire'
    | 'Zambia'
    | 'Zimbabwe'
