/**
 * Countries iso
 * {@link https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes}
 * @type {Object.<string, string>} 
 * @readonly
 */
export enum EFromIso {
    "Azerbaidjan" = "Azerbaijan",
    "Bolivia" = "Bolivia (Plurinational State of)",
    "Bosnia-Herzegovina" = "Bosnia and Herzegovina",
    "Cape Verde" = "Cabo Verde",
    "Czech Republic" = "Czechia",
    "East Timor" = "Timor-Leste",
    "Falkland Islands" = "Falkland Islands (Malvinas)",
    "Former Czechoslovakia" = "Czechia",
    "Former USSR" = "Russian Federation",
    "France (European Territory)" = "France",
    "French Guyana" = "Guyana",
    "Guadeloupe (French)" = "Guadeloupe",
    "Guam (USA)" = "Guam",
    "Guinea Bissau" = "Guinea-Bissau",
    "Heard and McDonald Islands" = "Heard Island and McDonald Islands",
    "Iran" = "Iran (Islamic Republic of)",
    "Ivory Coast (Cote D'Ivoire)" = "Ivory Coast",
    "Laos" = "Lao People's Democratic Republic",
    "Macau" = "Macao",
    "Macedonia" = "North Macedonia",
    "Martinique (French)" = "Martinique",
    "Micronesia" = "Micronesia (Federated States of)",
    "Netherlands Antilles" = "",
    "Neutral Zone" = "",
    "New Caledonia (French)" = "New Caledonia",
    "Pitcairn Island" = "Pitcairn",
    "Polynesia (French)" = "French Polynesia",
    "Reunion (French)" = "Reunion",
    "S. Georgia & S. Sandwich Isls." = "South Georgia and the South Sandwich Islands",
    "Saint Helena" = "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts & Nevis Anguilla" = "Saint Kitts and Nevis Saint Kitts and Nevis ",
    "Saint Tome (Sao Tome) and Princi" = "Sao Tome and Principe",
    "Saint Vincent & Grenadines" = "Saint Vincent and the Grenadines",
    "Slovak Republic" = "Slovakia",
    "South Korea" = "Korea, Republic of",
    "Spain (Canary Islands)" = "",
    "Svalbard and Jan Mayen Islands" = "Svalbard and Jan Mayen",
    "Swaziland" = "Eswatini",
    "Syria" = "Syrian Arab Republic",
    "Tadjikistan" = "Tajikistan",
    "Taiwan" = "Taiwan, Province of China",
    "Tanzania" = "Tanzania, the United Republic of",
    "United Kingdom" = "United Kingdom of Great Britain and Northern Ireland",
    "United Kingdom (Channel Islands)" = "",
    "United States" = "United States of America",
    "USA Minor Outlying Islands" = "United States Minor Outlying Islands",
    "Vatican City State" = "",
    "Venezuela" = "Venezuela (Bolivarian Republic of)",
    "Vietnam" = "Viet Nam",
    "Virgin Islands (USA)" = "Virgin Islands (U.S.)",
    "Wallis and Futuna Islands" = "Wallis and Futuna",
    "Yugoslavia" = "Greece",
    "Zaire" = "",
}